version: '3'

vars:
  SETUP_DEFAULT_PATTERN: ".*:setup"

tasks:
  setup:
    cmd: aqua install jqlang/jq@jq-1.7.1

  all:
    desc: Setup all tasks
    summary: |
      Similar to default but only to setup all tasks.

      The following variables are available:

      | VARIABLE       | DESCRIPTION                    | DEFAULT |
      |----------------|--------------------------------|---------|
      | `PATTERN`      | the task name pattern to match | `{{.SETUP_DEFAULT_PATTERN}}` |

      Examples:
        - `task` will run all default tasks if you use default as prefix
        - `task {{.TASK}}` will explicitly run all default tasks
    vars:
      PATTERN: '{{.PATTERN | default .SETUP_DEFAULT_PATTERN}}'

    # this one-line is pretty scary
    cmd: task -a --json | jq -c '[ (.tasks[] | select( .name | test({{.PATTERN | quote}})) | select( .name | index({{.TASK | quote}}) | not) ) | .name] | .[]' | xargs -n 1 -L1 -I'{}' sh -c 'task {} || exit 255'
